In [1]:
import pandas as pd

In [2]:
import math
import numpy as np

In [3]:
df=pd.read_csv('email.csv')

In [4]:
df.head()

x0  x1  x2  x3  x4  x5  class
0   1   1   1   0   1   1      1
1   1   0   0   1   1   0      0
2   1   0   1   1   0   0      1
3   1   1   0   0   1   0      0
4   1   1   0   1   0   1      1

In [5]:
df.isnull().sum()

x0       0
x1       0
x2       0
x3       0
x4       0
x5       0
class    0
dtype: int64

In [6]:
x=df.iloc[:,:-1]

In [7]:
y=df['class']

In [8]:
x['intercept']=1

In [9]:
x

x0  x1  x2  x3  x4  x5  intercept
0    1   1   1   0   1   1          1
1    1   0   0   1   1   0          1
2    1   0   1   1   0   0          1
3    1   1   0   0   1   0          1
4    1   1   0   1   0   1          1
5    0   1   1   1   1   0          1
6    1   1   1   0   1   1          1
7    1   0   0   1   1   0          1
8    1   0   1   1   0   0          1
9    1   1   0   0   1   0          1
10   1   1   0   1   0   1          1
11   1   1   0   1   1   0          1
12   0   1   1   0   1   1          1
13   1   0   0   1   1   0          1
14   0   0   1   1   0   0          1
15   1   1   0   0   1   0          1
16   1   1   0   1   0   1          1
17   1   1   0   1   1   0          1

In [10]:
x.columns

Index(['x0', 'x1', 'x2', 'x3', 'x4', 'x5', 'intercept'], dtype='object')

In [11]:
theta=np.array([0,0,0,0,0,0,0])
x=np.array(x)
y=np.array(y)

In [12]:
def grad(x,y,theta,epochs=1200,alpha=0.001):
    for i in range(epochs):
        f=x.dot(theta)
        h=1/(1+np.exp(-f))
        loss=h-y
        grad=x.T.dot(loss)/len(y)
        theta=theta-alpha*grad
    return theta

In [38]:
newt=grad(x,y,theta)
newt

array([-0.027621  ,  0.00135203,  0.15955516,  0.0014069 , -0.18896578,
        0.1920723 ,  0.00316211])

In [28]:
sample=np.array([[0,0,1,0,0,0,1],[1,1,1,1,0,1,1],[1,0,1,1,0,0,1],[0,1,0,1,0,0,1],[1,0,1,0,0,1,0],[1,0,0,0,1,1,0],[0,0,1,0,1,1,0],[0,0,0,0,0,1,0]])

In [29]:
sample=pd.DataFrame(sample)

In [30]:
sample.columns=['x0', 'x1', 'x2', 'x3', 'x4', 'x5', 'class']

In [32]:
sample['intercept']=1

In [33]:
sample

x0  x1  x2  x3  x4  x5  class  intercept
0   0   0   1   0   0   0      1          1
1   1   1   1   1   0   1      1          1
2   1   0   1   1   0   0      1          1
3   0   1   0   1   0   0      1          1
4   1   0   1   0   0   1      0          1
5   1   0   0   0   1   1      0          1
6   0   0   1   0   1   1      0          1
7   0   0   0   0   0   1      0          1

In [60]:
x_test=sample.drop('class',axis=1)

In [61]:
y_test=sample['class']

In [62]:
x_test=np.array(x_test)
y_test=np.array(y_test)

In [72]:
y_test

array([1, 1, 1, 1, 0, 0, 0, 0])

In [73]:
x_test

array([[0, 0, 1, 0, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 1],
       [1, 0, 1, 1, 0, 0, 1],
       [0, 1, 0, 1, 0, 0, 1],
       [1, 0, 1, 0, 0, 1, 1],
       [1, 0, 0, 0, 1, 1, 1],
       [0, 0, 1, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 1, 1]])

In [63]:
y_pred=1/(1+np.exp(-newt))

In [64]:
y_pred

array([0.49309519, 0.50033801, 0.53980438, 0.50035173, 0.45289863,
       0.54787099, 0.50079053])

In [65]:
y_pred[y_pred<0.5]=0
y_pred

array([0.        , 0.50033801, 0.53980438, 0.50035173, 0.        ,
       0.54787099, 0.50079053])

In [66]:
y_pred[y_pred>=0.5]=1

In [67]:
y_pred.astype('int')

array([0, 1, 1, 1, 0, 1, 1])

In [68]:
from sklearn.metrics import accuracy_score

In [75]:
y_test=y_test[:-1]

In [78]:
accuracy=accuracy_score(y_test,y_pred)

In [79]:
accuracy

0.5714285714285714